<?php

namespace AppBundle\Repository;

/**
 * GroupModuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupModuleRepository extends \Doctrine\ORM\EntityRepository
{
}
