<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($search){
        $query = $this->createQueryBuilder('u')
            ->where("u.name LIKE :search OR u.surname LIKE :search")
            ->setParameter("search", "%".$search."%")
            ->orderBy("u.name", "ASC")
            ->getQuery();
        return $query->getResult();
    }

}
